cat << EOF | oc apply -f -
apiVersion: k8s.nginx.org/v1
kind: VirtualServer
metadata:
  name: arcadia
spec:
  host: $nginx_ingress
  upstreams:
  - name: arcadia-main
    service: main
    port: 80
  - name: arcadia-app2
    service: app2
    port: 80
  - name: arcadia-app3
    service: pp3
    port: 80
  routes:
  - path: /
    action:
      pass: arcadia-main
  - path: /app2
    action:
      proxy:
        upstream: arcadia-app2
        rewritePath: /
  - path: /app3
    action:
      proxy:
        upstream: arcadia-app3
        rewritePath: /
EOF
